services:
  - type: web
    name: n8n
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install -g n8n
    startCommand: n8n
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: changeme123
      - key: WEBHOOK_URL
        value: https://your-subdomain.onrender.com
